spring.application.name: zti

server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      user: jochman
      password: UNvfPWLDHBVpc3rM
      database: Cluster0
#      uri: mongodb+srv://jochman:UNvfPWLDHBVpc3rM@cluster0.ry6wt0n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

